name: deploy_workflow
on:
  push:
    branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Testing
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build
              env:
                  CR_REGISTRY: crp5td2ej9d9m9e880v2
                  CR_REPOSITORY: tesser
                  IMAGE_TAG: ${{ github.sha }}
              run: docker build --tag cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .

            - name: Test
              env:
#                  CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
#                  CR_REPOSITORY: ${{ secrets.CR_REPOSITORY }}
#                  IMAGE_TAG: ${{ github.sha }}
                  CR_REGISTRY: crp5td2ej9d9m9e880v2
                  CR_REPOSITORY: tesser
                  IMAGE_TAG: ${{ github.sha }}

              run:  docker run cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG /usr/local/bin/python -m pytest


            - name: Login to Yandex Cloud Container Registry
              id: login-cr
              uses: yc-actions/yc-cr-login@v1
              with:
                  yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

            - name: Push Image To YC
              env:
                  CR_REGISTRY: crp5td2ej9d9m9e880v2
                  CR_REPOSITORY: tesser
                  IMAGE_TAG: ${{ github.sha }}
              run: docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG


#      - name: Deploy COI YC
#        uses: yc-actions/yc-coi-deploy@v1.0.1
#        with:
#          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
##          folder-id: ${{ secrets.YC_FOLDER_ID }}
#          VM-name: test_coi
##          vm-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
#          vm-cores: 1
#          vm-platform-id: 'standard-v2'
#          vm-memory: 512Mb
#          vm-disk-size: 30Gb
#          vm-core-fraction: 5
##          vm-subnet-id: ${{ secrets.YC_SUBNET_ID }}
##          docker-compose-path: './yandex-cloud/docker-compose.yc.yaml'
##          user-data-path: './yandex-cloud/user-data.yaml'
