name: deploy_workflow
on:
  push:
    branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Testing
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build
              env:
                  CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
                  CR_REPOSITORY: ${{ secrets.CR_REPOSITORY }}
                  IMAGE_TAG: ${{ github.sha }}
              run: docker build --tag cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .

            - name: Test
              env:
                  CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
                  CR_REPOSITORY: ${{ secrets.CR_REPOSITORY }}
                  IMAGE_TAG: ${{ github.sha }}

              run:  docker run cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG /usr/local/bin/python -m pytest


            - name: Login to Yandex Cloud Container Registry
              id: login-cr
              uses: yc-actions/yc-cr-login@v1
              with:
                  yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

            - name: Push Image To YC
              env:
                  CR_REGISTRY: crp5td2ej9d9m9e880v2
                  CR_REPOSITORY: tesser
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
                  docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
                
            - name: Deploy Serverless Container
              id: deploy-sls-container
              uses: yc-actions/yc-sls-container-deploy@v2
              with:
                yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
                container-name: worddetector-test
                folder-id: ${{ secrets.FOLDER_ID }}
                revision-service-account-id: ${{ secrets.SERVICE_ACCOUNT_ID }}
                revision-cores: 1
                revision-memory: 512Mb
                revision-core-fraction: 100
                revision-concurrency: 8
                revision-image-url: cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
                revision-execution-timeout: 10

