name: deploy_workflow
on:
  push:
    branches: ["master"]

jobs:
  lint:
      env:
        API_TOKEN: ${{secrets.API_TOKEN}}
      runs-on: ubuntu-latest
      steps:
        - name: build
          run: ls && pwd