name: deploy_workflow
on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: docker build --tag test_image .

      - name: Test
        run:  docker run test_image /usr/local/bin/python -m pytest